practice1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shorturl.urls')),
]

shorturl/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'shorturl'
urlpatterns = [
    path('', views.index,name="index"),
    path('<str:short_url>', views.get_url,name="get_url"),
]

shorturl/models.py
from django.db import models

class Url(models.Model):
	url = models.CharField(max_length=200)
	shortUrl = models.CharField(max_length=200)

	def __str__(self):
		return self.url

shorturl/views.py
from django.shortcuts import render
import pdb
from .classShortUrl import ShortUrl
from shorturl.models import Url


def index(request):
	# pdb.set_trace()
	urls = Url.objects.all().order_by('-id')
	context = {
		'urls':urls,
		'host':request.META['HTTP_HOST'] 
	}
	if request.method == 'POST':
		url_string = request.POST['url']
		urlinstance = ShortUrl(url_string)
		# pdb.set_trace()
		short_url = urlinstance.convert_url()
		url = Url(url=url_string,shortUrl=short_url)
		try:
			if url.save():
				return render(request,'shorturl/index.html',context)
		except Exception as e:
			return e
	return render(request,'shorturl/index.html',context)

def get_url(request,short_url):
	try:
		url_string = Url.objects.filter(shortUrl=short_url)[0]
	except Exception as e:
		context = {
			'url':"no se encontro"
		}
		return render(request,'shorturl/original_url.html',context)
	else:

		context = {
			'url':url_string
		}
		return render(request,'shorturl/original_url.html',context)

shorturl/templates/base.html
{%load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	{%block title %}<title>Document</title>{%endblock%}
	<meta charset="UTF-8">
	  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	
</head>
<body>

	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-2">
				{%block sidebar%}
					<ul>
						<li><a href="">index </a></li>
						<li><a href="">demas </a></li>
					</ul>
				{%endblock%}
			</div>
			<div class="col-sm-10">
				
				{% block content %}{% endblock%}
			</div>

		</div>
	</div>
	
</body>
</html>

shorturl/templates/shorturl/index.html
{% extends "base.html" %}
{% block content %}
<h1>The shorterurl </h1>

<form action="{% url 'shorturl:index' %}" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="url">url</label>
		<input type="text" class="form-control" id="" name="url">
	</div>
	<button type="submit" class="btn btn-primary">submit</button>
</form>


{% if urls %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">url</th>
      <th scope="col">shorturl</th>
      <th scope="col">full url</th>
    </tr>
  </thead>
  <tbody>
  	{%for url in urls%}
    <tr>
      <th scope="row">{{url.id}}</th>
      <td>{{url.url}}</td>
      <td>{{url.shortUrl}}</td>
    </tr>
  	{%endfor%}
  </tbody>
</table>
{% else %}
<h3>no hay registros en la base de datos</h3>
{% endif %}


{% endblock %}

shorturl/templates/shorturl/original_url.html
<h1>{{url}}</h1>